### PR TITLE
Add android screenshots

### PR DESCRIPTION
**Pull request by vj-abishek**
@gurrrung Done.

### CODE REVIEW

**Comment by vj-abishek** [comment]
#60

**Comment by vj-abishek** [comment]
@gurrrung Is this okay?

**Comment by gurrrung** [comment]
Please read my comment https://github.com/Tele-Bots/CovidBot/pull/91#pullrequestreview-501516782, I want all images in a single line further each image should have only one command (you can delete older messages for each screenshot).

**Comment by vj-abishek** [comment]
Okay will fix it soon

**Comment by vj-abishek** [comment]
@gurrrung the welcome message will be in every screenshot if you delete previous messages. Is that okay?

**Comment by vj-abishek** [comment]
@gurrrung if I delete the previous message means there will be a welcome message in every screenshot, is that okay?

**Comment by gurrrung** [comment]
No, I don't want that welcome message too. I just want each screen to have the command as the first message and bot reply as the second message, would that be possible?

**Comment by vj-abishek** [comment]
If I delete the welcome message, it is starting from the beginning. The only solution is if I don't delete the `/start` message, it not starting from the beginning. But there will be `/start`  in every screenshot. Is that okay?

**Comment by gurrrung** [comment]
> If I delete the welcome message, it is starting from the beginning.

I want it to start from the beginning for each screenshot.

**Comment by vj-abishek** [comment]
> > If I delete the welcome message, it is starting from the beginning.
> 
> I want it to start from the beginning for each screenshot.

If I start from the beginning, there will be welcome message

**Comment by vj-abishek** [comment]
The conversation is only starting when `/start` message is typed. If I type that message a welcome message is shown. If I delete the bot reply and my `/start` message, I need to press `/start` button again to start a conversation

**Comment by vj-abishek** [comment]
I think the images that are sent in this PR itself okay. If it is okay for you, I will align the images in one line

**Comment by vj-abishek** [comment]
@gurrrung what I need to do?

**Comment by gurrrung** [comment]
1) Start
2) Send the required command
3) Delete the /start message and its reply.

**Comment by vj-abishek** [comment]
Okay, Will be done soon.

**Comment by vj-abishek** [comment]
@gurrrung done 👍

**Comment by gurrrung** [comment]
I'm happy with images, can you decrease the image size because they are not aligning in a lint due to size. https://github.com/vj-abishek/CovidBot

**Review by gurrrung — APPROVED** [review]
LGTM

**Comment by gurrrung** [comment]
Merged, thanks for the contribution.

**Comment by vj-abishek** [comment]
@gurrrung Could you mark this PR as hacktoberfest-accepted. It seems guidelines have changed a bit to avoid spam.

**Pull request merged**
