### PR TITLE
Add Android Screenshots

### PR DESCRIPTION
**Pull request by vj-abishek**

### CODE REVIEW

**Comment by vj-abishek** [comment]
#60

**Comment by vj-abishek** [comment]
@gurrrung is this okay?

**Review by gurrrung — CHANGES_REQUESTED** [review]
I want a single command in a single screenshot. I don't want the upper section (which contains the battery indicator, please crop it). Further, in Readme, I want the three images in a single line, perfectly placed.

**Comment by vj-abishek** [comment]
Okay

**Comment by gurrrung** [comment]
Are you interested in completing this?

**Comment by vj-abishek** [comment]
@gurrrung done. Here is the PR #92

**Pull request closed without merging**
